apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: redis
  name: redis
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: redis
    spec:
      containers:
      - image: redis:alpine
        imagePullPolicy: IfNotPresent
        name: redis
        ports:
        - containerPort: 6379
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
