---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: voting-app
  name: voting-app
  namespace: default
spec:
  selector:
    run: voting-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
